name: Frontend CI/CD Pipeline

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from your repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js to build the frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # or your Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project with Vite
      - name: Build the project
        run: npm run build

      # Step 5: Deploy the build to the EC2 server
      - name: Deploy to EC2
        run: |
          eval "$(ssh-agent -s)"  # Start the SSH agent
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -  # Add the SSH key
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "rm -rf $EC2_PATH/*"  # Clean up the old files
          scp -r dist/* $EC2_USER@$EC2_HOST:$EC2_PATH  # Copy new files
          ssh $EC2_USER@$EC2_HOST "sudo systemctl restart nginx"  # Restart Nginx
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_PATH: ${{ secrets.EC2_PATH }}
