name: React TypeScript CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: ['20.x']

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: |
        npm install

    # Step to create or update the .env file with secrets
    - name: Create or Update .env File
      run: |
        if [ ! -f .env ]; then
          touch .env
        fi
        echo "VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }}" >> .env
        echo "VITE_BASE_API_URL=${{ secrets.VITE_BASE_API_URL }}" >> .env
      shell: bash

    - name: Build Project
      run: |
        npm run build --if-present

    - name: Test Nginx Configuration
      run: |
        sudo nginx -t

    - name: Restart Nginx
      run: |
        sudo systemctl restart nginx
