name: React TypeScript CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Navigate to the project directory and install dependencies
      run: |
        # Navigate to the manually cloned project directory
        cd /home/ubuntu/Support-System-Frontend
        # List files to ensure we are in the correct directory
        ls -la
        npm install

    - name: Build the project
      run: |
        # Navigate to the project directory
        cd /home/ubuntu/Support-System-Frontend
        npm run build --if-present

    - name: Test Nginx Configuration
      run: |
        sudo nginx -t

    - name: Restart Nginx
      run: |
        sudo systemctl restart nginx
