name: React TypeScript CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

  steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - name: Test Nginx Configuration
      run: |
        sudo nginx -t

    - name: Restart Nginx
      run: |
        sudo systemctl restart nginx